In [35]:
import numpy as py
import matplotlib.pyplot as plt
import pandas as pd

In [43]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names=['spal_len','sepal_wid','petal_len','petal_wid','class']
dataset = pd.read_csv(url,names=names , header=None )
# dataset.info
# dataset.head()

In [37]:
dataset['class'].unique()   # show name of classes

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [38]:
x = dataset.iloc[:,0:-1]   # 4 columns without index
y = dataset.iloc[:,4]      # class

In [39]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

In [40]:
# pre_proccessing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test  = scaler.transform(x_test)

In [41]:
# implement KNN
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x_train , y_train)
y_pred = classifier.predict(x_test)

In [45]:
from sklearn.metrics import classification_report , confusion_matrix

print(' classification_report :  \n  {0} '.format(classification_report(y_test,y_pred)))
print('--------------------------------------------------------')
print(' confusion_matrix :  \n  {0} '.format(confusion_matrix(y_test,y_pred)))


 classification_report : 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.88      1.00      0.93         7

       accuracy                           0.97        30
      macro avg       0.96      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30
 
--------------------------------------------------------
 confusion_matrix : 
 [[14  0  0]
 [ 0  8  1]
 [ 0  0  7]] 
